# Generated by Django 4.2 on 2023-04-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nameparent',
            options={'verbose_name': 'Родитель звена', 'verbose_name_plural': 'Родитель звена'},
        ),
        migrations.AlterField(
            model_name='nameparent',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='treenodemodel',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='menu_view.nameparent', verbose_name='Родитель'),
        ),
    ]
