# Generated by Django 4.2 on 2023-04-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_view', '0002_alter_nameparent_options_alter_nameparent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treenodemodel',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
