# Generated by Django 4.2 on 2023-05-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_view', '0003_alter_treenodemodel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='treenodemodel',
            name='number_menu',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
